# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-01 05:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToLetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('area', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='tolet')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='tolet')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='tolet')),
                ('open', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
