# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-08 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0002_auto_20190108_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areamodel',
            name='city',
        ),
    ]
